#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: 5
#  username: root
#  password: 'password'
#  host: mysql

#development:
#  <<: *default
#  database: aviasales_killer_development

#test:
#  <<: *default
#  database: aviasales_killer_test


default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
